version: '3.4'
services:
  sql.data:
    environment:
      - SA_PASSWORD=SuperStrongPassword1
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433" 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
  kibana:
    ports:
    - "5601:5601"
    networks:
    - docker-network
networks:
  default:
    driver: bridge
  docker-network:
    driver: bridge
volumes:
  elasticsearch-data: